"""Add is_admin to users

Revision ID: fd215dfad484
Revises: 60f9094f81af
Create Date: 2025-04-08 12:59:51.972987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd215dfad484'
down_revision: Union[str, None] = '60f9094f81af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_schema', 'user_permissions', type_='unique')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.create_unique_constraint('uq_user_schema', 'user_permissions', ['user_id', 'schema_name'])
    # ### end Alembic commands ###
